### ISSUE TITLE
Vertical bar as delimiter

### ISSUE THREAD

**Issue by linuxion** [Blockchair/Blockchair.Whitepapers#82]
Hi @RustamSultanov,

Please pay attention that vertical bar `|` should be used only as separator. If you use it anywhere, it will be inconvenient to process the list with a standard functions. 

For example, line 1539 must be fixed.

Thank you!

**Comment by RustamSultanov** [comment]
I think, that is some legasy description in this line.  Usually I use pipe only as separetor.  

Thank you!
